Update man-redis

diff --git a/conf/redis/man-redis b/conf/redis/man-redis
--- a/conf/redis/man-redis
+++ b/conf/redis/man-redis
@@ -10,21 +10,21 @@ c=${log_dir}/${redis_dir}
 start() {
     netstat -unltp | awk -F':' '{print $2}' | grep -w ${port} &> /dev/null
     if [ $? -ne 0 ];then
-        $a $b/${port}/${port}.conf >> $c/redis_${1}.log &
+        $a $b/${port}/${port}.conf >> $c/redis_${port}.log &
     fi
 }
 
 stop() {
     netstat -unltp | awk -F':' '{print $2}' | grep -w ${port} &> /dev/null
     if [ $? -eq 0 ];then
-        pid=`cat ${install_dir}/${redis_dir}/cluster/${1}/redis_${1}.pid `
+        pid=`cat ${install_dir}/${redis_dir}/cluster/${port}/redis_${port}.pid `
         kill -9 $pid &> /dev/null
     fi
 }
 
 status() {
     netstat -unltp | awk -F':' '{print $2}' | grep -w ${port} &> /dev/null
-    [ $? -eq 0 ] && echo "redis port:${1} ok" || echo "redis port:${1} error"
+    [ $? -eq 0 ] && echo "redis port:${port} ok" || echo "redis port:${port} error"
 }
 
 
